version: '3.8'

services:
  app:
    build: .
    container_name: goodcontent-container
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: npm start --prefix server
